# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twelvedata < Formula
  desc "Twelve Data CLI — the official command-line client for the Twelve Data API"
  homepage "https://twelvedata.com"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.6/twelvedata-darwin-x64.tar.gz"
      sha256 "9d6b3c73f8cd4e6f07d3ebf3c0e405e60d3f7635338717be9a57c44924023ff4"

      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.6/twelvedata-darwin-arm64.tar.gz"
      sha256 "d4563f45bf32255eda889e64eb9cd70bbc0ec55be14c5344b21544ff394c669e"

      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.6/twelvedata-linux-x64.tar.gz"
      sha256 "8f548cb041195cf4e362c3980db76c48c887317cd7a07652c4491337d0db3147"
      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.6/twelvedata-linux-arm64.tar.gz"
      sha256 "b6ca7d9759744d23a2092fc49657d807cfb13e44a8c59f6575e962a7ae8395dd"
      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/twelvedata --version")
  end
end
