# This file was generated by GoReleaser. DO NOT EDIT.
cask "twelvedata" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "ce0fad8f16d8efe0b3d337eec8b10c58ca4a44d3277225a09ea346e1dbfdc6c9"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-darwin-x64.tar.gz"
    end
    on_arm do
      sha256 "9a8c4dd115dec5251c766503c565e8b8aed005532f11cd0815b3875e723c4772"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b4f3e2b1b07dcefe6df867881e0e3be910ce52b9d7462f7cd31a493f8d52160"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-linux-x64.tar.gz"
    end
    on_arm do
      sha256 "92a0865d7d059230fef17551c7cbfc05c4709ae2b7caa42591190ad1191cd112"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-linux-arm64.tar.gz"
    end
  end

  name "twelvedata"
  desc "Twelve Data CLI — the official command-line client for the Twelve Data API,"
  homepage "https://twelvedata.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twelvedata"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twelvedata"]
    end
  end

  # No zap stanza required

end
