# This file was generated by GoReleaser. DO NOT EDIT.
cask "twelvedata" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "ff7097a1fc2a0c34065f1f4fa572a04100e3fc343074c822736e1f000f921607"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-darwin-x64.tar.gz"
    end
    on_arm do
      sha256 "828d75c1c7623e986d0f94c51180f596cb600c22a3aa625fa14a2e95eb549022"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "61ab42970b26c452bc5e588a8087f20d91502fd799a08663c800d8f9e8efe9af"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-linux-x64.tar.gz"
    end
    on_arm do
      sha256 "deb9ebf1467f4f2bc88d1e8a2e354b86b5367637e441aecc798929f4f4d9b308"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-linux-arm64.tar.gz"
    end
  end

  name "twelvedata"
  desc "Twelve Data CLI — the official command-line client for the Twelve Data API,"
  homepage "https://twelvedata.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twelvedata"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twelvedata"]
    end
  end

  # No zap stanza required

end
