# This file was generated by GoReleaser. DO NOT EDIT.
cask "twelvedata" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "24f9bf9ffe8238ab0495b3507132b0eb0a56f8edc6253ce0ae2ba4eb605bfe08"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-darwin-x64.tar.gz"
    end
    on_arm do
      sha256 "dea8db99c4c4b72c90409df42edd6360748603aa13915b6a439a97279c707b0e"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c86ea12df5a7873be37efd2fbf1fee3d7601ddf70dbdccc3e37187ca60b7ede"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-linux-x64.tar.gz"
    end
    on_arm do
      sha256 "b468b6bb237cf4314fb12379c70f70e23b1d92772237e72b2f7022738f5e3e04"
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v#{version}/twelvedata-linux-arm64.tar.gz"
    end
  end

  name "twelvedata"
  desc "Twelve Data CLI — the official command-line client for the Twelve Data API,"
  homepage "https://twelvedata.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twelvedata"
  generate_completions_from_executable "twelvedata",
    base_name: "twelvedata",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twelvedata"]
    end
  end

  # No zap stanza required

end
