# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twelvedata < Formula
  desc "Twelve Data CLI — the official command-line client for the Twelve Data API"
  homepage "https://twelvedata.com"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.10/twelvedata-darwin-x64.tar.gz"
      sha256 "6aa365f481e2c570ed67da85d88192712bed6a4b39aac6142123a494b8a56b88"

      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.10/twelvedata-darwin-arm64.tar.gz"
      sha256 "dd7b43c83649f3a9ede93e4c197e0e479f138650b6792de5fddf0bd18395cf8a"

      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.10/twelvedata-linux-x64.tar.gz"
      sha256 "eb78bd50eb3e4b1e22d78cd59589671b5b13a8c666b937caa7a6c699181efcf7"
      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.10/twelvedata-linux-arm64.tar.gz"
      sha256 "34f7bbff2ebc51260ceb8d87ca2a2863e68fe468745691868ab3224503eccaa8"
      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/twelvedata --version")
  end
end
