# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twelvedata < Formula
  desc "Twelve Data CLI — the official command-line client for the Twelve Data API"
  homepage "https://twelvedata.com"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.8/twelvedata-darwin-x64.tar.gz"
      sha256 "3c7d8b8751236e98bef10053fa7dafaeebf941b9e412a14ff717b3980da4c0b8"

      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.8/twelvedata-darwin-arm64.tar.gz"
      sha256 "4b17c6554d3eab5d03c1966f99712bbfc9b1ee8e42449a87853116501bec86db"

      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.8/twelvedata-linux-x64.tar.gz"
      sha256 "a2326ca9e2ab8e8371200f48a3db1c16c0786cbf8bee454e8280adc5e730855f"
      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.8/twelvedata-linux-arm64.tar.gz"
      sha256 "9f16f548faf6891c03ace3423b260f47b7231bdc3708856127bc34b35f1ff55a"
      define_method(:install) do
        bin.install "twelvedata"
        generate_completions_from_executable(
          bin/"twelvedata",
          "completion",
          shells: [:bash, :zsh, :fish, :pwsh],
          shell_parameter_format: :cobra,
        )
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/twelvedata --version")
  end
end
