# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twelvedata < Formula
  desc "Twelve Data CLI — the official command-line client for the Twelve Data API,"
  homepage "https://twelvedata.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.0/twelvedata-darwin-x64.tar.gz"
      sha256 "2ecc4c4b6320727a69dcc7e37e8390fc20f7cf9da7d9104a6471ea93b70511dd"

      define_method(:install) do
        bin.install "twelvedata"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.0/twelvedata-darwin-arm64.tar.gz"
      sha256 "44dc201fa56c230d83565aa2f66863498aca825a8629ed97e7f12a0de12472d3"

      define_method(:install) do
        bin.install "twelvedata"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.0/twelvedata-linux-x64.tar.gz"
      sha256 "4c2573d08beeb67f166c1127454bb257dd5e9c1ccbcbced47df15378f10cc2cb"
      define_method(:install) do
        bin.install "twelvedata"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twelvedata/twelvedata-cli/releases/download/v1.0.0/twelvedata-linux-arm64.tar.gz"
      sha256 "e9659b9d8eafbd50ab91b1d19b02f67fa4c46ac940ed929e809f6b45125aa799"
      define_method(:install) do
        bin.install "twelvedata"
      end
    end
  end

  test do
    system "#{bin}/twelvedata", "--version"
  end
end
